name: example
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  path: ^1.8.0
  custom_lint: ^0.7.5

dev_dependencies:
  lints: ^5.0.0
  custom_lint_lsp_bug:
    path: ../
  analysis_server_client:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/analysis_server_client
      ref: 3.8.0-278.3.beta
  pub_semver: ^2.2.0
